import { isFirebaseReady } from '@/lib/firebase-admin';
import type { FullProject } from '@/types';

// Mock data for demo mode when Firebase is not available
const MOCK_PROJECTS: FullProject[] = [
  {
    id: 'demo-project-1',
    caseNumber: 'YPE-2025-001',
    name: '智慧製造執行方案 (MES 導入)',
    projectPurpose: '導入智慧製造系統以提升生產效率',
    currentStatusAndIssues: '目前進度正常，正在進行第二階段測試',
    yiehPhuiProjectManager: '王大明',
    tpmOfficeContact: '李小華',
    egigaContact: '張志偉',
    status: 'active',
    createdBy: 'user-1',
    createdAt: '2025-01-15T08:00:00Z',
    subProjects: [
      {
        id: 'demo-sub-1',
        projectId: 'demo-project-1',
        projectName: '智慧製造執行方案 (MES 導入)',
        projectCaseNumber: 'YPE-2025-001',
        name: '產線數據收集模組',
        owner: 'user-2',
        ownerName: '陳小明',
        createdAt: '2025-02-01T08:00:00Z',
        isOverdue: false,
        isParentOnHold: false,
        latestLog: {
          id: 'demo-log-1',
          subProjectId: 'demo-sub-1',
          executionSummary: '已完成感測器安裝與數據串接，正在進行資料驗證。',
          nextWeekPlan: '完成資料清洗模組開發，開始進行歷史數據回填。',
          roadblocks: '',
          completionPercentage: 65,
          createdBy: 'user-2',
          createdByName: '陳小明',
          updatedAt: '2025-04-22T08:00:00Z',
        },
      },
      {
        id: 'demo-sub-2',
        projectId: 'demo-project-1',
        projectName: '智慧製造執行方案 (MES 導入)',
        projectCaseNumber: 'YPE-2025-001',
        name: '即時看板系統',
        owner: 'user-3',
        ownerName: '林美玲',
        createdAt: '2025-02-01T08:00:00Z',
        isOverdue: true,
        isParentOnHold: false,
        latestLog: {
          id: 'demo-log-2',
          subProjectId: 'demo-sub-2',
          executionSummary: 'Dashboard UI 框架已完成，待後端 API 對接。',
          nextWeekPlan: '進行 API 整合測試。',
          roadblocks: '後端 API 文件尚未定版，無法進行整合開發。',
          completionPercentage: 40,
          createdBy: 'user-3',
          createdByName: '林美玲',
          updatedAt: '2025-04-10T08:00:00Z',
        },
      },
      {
        id: 'demo-sub-3',
        projectId: 'demo-project-1',
        projectName: '智慧製造執行方案 (MES 導入)',
        projectCaseNumber: 'YPE-2025-001',
        name: '報表匯出功能',
        owner: 'user-2',
        ownerName: '陳小明',
        createdAt: '2025-03-01T08:00:00Z',
        isOverdue: false,
        isParentOnHold: false,
        latestLog: null,
      },
    ],
  },
  {
    id: 'demo-project-2',
    caseNumber: 'YPE-2025-002',
    name: '能源管理系統升級',
    projectPurpose: '升級既有能源管理系統以符合 ISO 50001',
    currentStatusAndIssues: '等待設備採購核准',
    yiehPhuiProjectManager: '張志偉',
    tpmOfficeContact: '王大明',
    egigaContact: '陳小明',
    status: 'on-hold',
    createdBy: 'user-1',
    createdAt: '2025-03-01T08:00:00Z',
    isOnHold: true,
    onHoldStartDate: '2025-04-01T08:00:00Z',
    onHoldReason: '設備採購流程延宕',
    onHoldNotes: '預計 2025 年 Q3 恢復',
    subProjects: [
      {
        id: 'demo-sub-4',
        projectId: 'demo-project-2',
        projectName: '能源管理系統升級',
        projectCaseNumber: 'YPE-2025-002',
        name: '電力監控模組更新',
        owner: 'user-3',
        ownerName: '林美玲',
        createdAt: '2025-03-15T08:00:00Z',
        isOverdue: false,
        isParentOnHold: true,
        latestLog: {
          id: 'demo-log-3',
          subProjectId: 'demo-sub-4',
          executionSummary: '規格書已完成，等待設備到貨。',
          nextWeekPlan: '暫緩中。',
          roadblocks: '設備採購延遲，預計延後兩個月。',
          completionPercentage: 20,
          createdBy: 'user-3',
          createdByName: '林美玲',
          updatedAt: '2025-04-01T08:00:00Z',
        },
      },
    ],
  },
];

export async function getDemoProjects(): Promise<FullProject[]> {
  return MOCK_PROJECTS;
}
